test_that("watch() watches", {
  x <- 0L
  dir <- file.path(tempdir(), "watcher-test")
  subdir <- file.path(dir, "subdir")
  dir.create(dir)
  dir.create(subdir)
  w <- watcher(dir, recursive = TRUE, callback = function() x <<- x + 1L)
  expect_s3_class(w, "watch")
  skip_if_not_installed("later")
  expect_true(watcher_start(w))
  Sys.sleep(1L)
  file.create(file.path(subdir, "oldfile"))
  later::run_now(2L)
  expect_equal(x, 1L)
  file.rename(file.path(subdir, "oldfile"), file.path(subdir, "newfile"))
  later::run_now(2L)
  expect_equal(x, 2L)
  file.remove(file.path(subdir, "newfile"))
  later::run_now(2L)
  expect_equal(x, 3L)
  file.create(file.path(dir, "oldfile"))
  later::run_now(2L)
  expect_equal(x, 4L)
  file.rename(file.path(dir, "oldfile"), file.path(dir, "newfile"))
  later::run_now(2L)
  expect_equal(x, 5L)
  file.remove(file.path(dir, "newfile"))
  later::run_now(2L)
  expect_equal(x, 6L)
  expect_true(watcher_stop(w))
  unlink(dir, recursive = TRUE, force = TRUE)
  rm(w)
  gc()
})
