test_that("watcher() watches", {
  x <- 0L
  dir <- file.path(tempdir(), "watcher-test")
  subdir <- file.path(dir, "subdir")
  dir.create(dir)
  dir.create(subdir)
  w <- watcher(dir, recursive = FALSE, callback = NULL)
  expect_s3_class(w, "watch")
  expect_false(attr(w, "recursive"))
  expect_false(attr(w, "active"))
  expect_true(watcher_start(w))
  expect_true(attr(w, "active"))
  Sys.sleep(1L)
  file.create(file.path(dir, "testfile"))
  Sys.sleep(1L)
  expect_true(watcher_stop(w))
  expect_false(attr(w, "active"))
  w <- watcher(dir, recursive = TRUE, callback = function() x <<- x + 1L)
  expect_output(print(w))
  expect_s3_class(w, "watch")
  expect_true(attr(w, "recursive"))
  expect_false(attr(w, "active"))
  skip_if_not_installed("later")
  expect_true(watcher_start(w))
  expect_true(attr(w, "active"))
  Sys.sleep(1L)
  file.create(file.path(subdir, "oldfile"))
  later::run_now(2L)
  expect_equal(x, 1L)
  file.rename(file.path(subdir, "oldfile"), file.path(subdir, "newfile"))
  later::run_now(2L)
  expect_equal(x, 2L)
  file.remove(file.path(subdir, "newfile"))
  later::run_now(2L)
  expect_equal(x, 3L)
  file.create(file.path(dir, "oldfile"))
  later::run_now(2L)
  expect_equal(x, 4L)
  file.rename(file.path(dir, "oldfile"), file.path(dir, "newfile"))
  later::run_now(2L)
  expect_equal(x, 5L)
  file.remove(file.path(dir, "newfile"))
  later::run_now(2L)
  expect_equal(x, 6L)
  expect_true(watcher_stop(w))
  expect_false(attr(w, "active"))
  unlink(dir, recursive = TRUE, force = TRUE)
})

test_that("watcher() error handling", {
  expect_error(watcher(callback = "callback"), "must be a function")
  expect_false(watcher_start("test"))
  expect_false(watcher_stop("test"))
})
